### PR TITLE
Update COSE information; add hashtags

### PR DESCRIPTION
**Pull request by cabo**

### CODE REVIEW

**Comment by chrysn** [comment]
A few notes with my designated-expert hat on:
* 512 out of 1+2 are roughly equivalent to 2 out of 1+1 (but actually have less impact, for 1+2 is less heavily contested)
* Still, it's worth comparing the construction with a 1+1 allocation and using the numbers: for a hash with encoded size k (typically byte strings 1+1+data, as data's length is > 24), the proposal results in 1+2+k=3+k bytes, whereas using a 1+1 tag (`tagged = #6.x([regnum, hash])`)  results in 1+1+1+e+k bytes, with e being 1, 2 or (for larger numbers) 3, for a total of at least 4+k bytes (often more), so the encoding is relatively efficient.

And questions:
* This reserves a range, of which some (eg. -27, although that does receive special handling) will not actually be usable because their COSE entries are not hash functions. Will those be freed up as soon as the COSE registry is populated? If so, what'll be the mechanism for those to happen? (Like, informal mail to IANA, or a document just asking for one of the tags?)
* Is there a particular reason -27 was chosen? There's a large range below -25 that'd be eligible.

**Comment by chrysn** [comment]
More questions:
* Does the presence of the tag have any equivalence behavior of cbor-packed? I.e. does the hash stand in for the hashed content, or for the CBOR item that would be serialized into the hashed content?
* There is another registry for hash values, the ["Named Information Hash Algorithm Registry"](https://www.iana.org/assignments/named-information/named-information.xhtml), which is more dense. COSE hopefully had good reasons to have its relatively weakly typed registry and not go with that one; do the same reasons apply here?

**Comment by cabo** [comment]
Unfortunately, tags are always unary (one data item), and therefore 1+1+array+1+0 is usually more expensive than 1+2.
-27 cannot be used here as defined in the COSE registry, because the data structure expected is not a byte string.  That is why we allocate it to the more wide-ranged structure with the embedded array.  That way we also don't have an ugly hole.

**Comment by cabo** [comment]
I don't think the hashes get full stand-in power unless that is conferred by the structures around it.  That could be clarified in the text.

**Comment by cabo** [comment]
Tag numbers for the ni hash registry could be added when or if they are needed.
New registrations unfortunately don't seem to have numbers, making the ni registry less useful.
One recent example for an important embedded protocol is SUIT, which also uses COSE hash algorithm numbers (in a more complex overall structure, so they don't need this set of tags).

**Comment by chrysn** [comment]
Thanks for the update -- I agree that they better not stand in in general.

If the numeric component of the ni registry has fallen into disuses, that'd be a good point to state when picking the COSE registry as the base of hash values (like, "there's that other one but it isn't used with numbers any more").

I still don't understand why -27 is special (from what is in the COSE registry, -25 and -26 also are ECDH algorithms that are not hash algorithms), and the question about repurposing clearly-not-a-hash tag values (as is done already in the document for 18541).

**Comment by cabo** [comment]
18541 *is* -27.  Maybe I don't follow... -27 is taken by RFC 9360.  The data structure it uses, COSE_Certhash, is actually the same we use for General_COSE_Hash<alg, value>, so the analogy is kept up every further.

**Comment by chrysn** [comment]
Aren't we mixing up registries here?

The range that's being requested is mapped to "COSE Algorithms". There, -16 is SHA256 (as the current draft points out). -27 in the same registry is ECDH-SS + HKDF-256, which is not a hash function.

The -27 registered in 9360 is "Thumbprint for the sender's X.509 certificate", and matches the use in the draft, but is in "COSE Header Algorithm Parameters".

This mixing works here because "ECDH-SS + HKDF-256" is not a hash function. But that's coincidence and not a pattern I'd consider practical to establish.

So, coming back to my original questions:
* "ECDH-SS + HKDF-256" being -27 in COSE Algorithms means that 18541 is not used in the range allocated for Standard_COSE_Hash. The same is true for about 3/4 of the other code points that are currently allocated, and will become true over time. Is it the general idea that those are now or later freed up for use by whatever else could use them?
  * In particular, should we (not for immediate action but for futureproofness) consider that some tags could be allocated for "This data item describes a symmetric {A128GCM, ...} key"? Those could then even use the same range, because no entry in COSE algorithms is both a hash function and symmetric encryption algorithm (or could it be)?
  
  If we have any shenanigans like that in mind, I think we should keep the full range reserved. If not, I think we should state that any number registered in COSE algorithms that is not a hash function (eg. -27 which is some ECDH) is for grabs again (and this document does grab a particular one).
* With that, is there any particular rationale for picking 18541 for the extension point? Its value is arbitrary within that range (with `hashmiddle .plus (-27)` having purely mnemonic value, just in case someone knows hashmiddle and the 27 by heart), and I think it's more confusing than helpful.

**Comment by chrysn** [comment]
The changes in #4 address my concerns by placing the special tag at offset 0 which is reserved. An added note states that non-hash tags could still be used, retaining change control of them ("could be defined by a future version of this specification") which is fine.

As for the rationale of the pivot point, it is helpful to look at the ASCII version of the binary produced for common hash functions

This addresses my questions, clearing the latest allocation request.

**Pull request merged**
